name: Build KSO Download Turbo Ultra v1 PRO
on: [workflow_dispatch]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: {python-version: '3.10'}
    - name: Install deps
      run: |
        pip install --upgrade pip
        pip install pyinstaller yt-dlp PyQt6 PyQt6-WebEngine==6.6.1 keyboard cryptography psutil speedtest-cli plyer
    - name: Build EXE
      run: |
        pyinstaller --noconsole --onefile --name "KSO_Download_Turbo_Ultra_v1" --hidden-import=PyQt6.QtWebEngineWidgets --hidden-import=PyQt6.QtWebEngineCore --hidden-import=keyboard --hidden-import=cryptography --hidden-import=plyer main.py
    - uses: actions/upload-artifact@v4
      with:
        name: KSO-Download-Turbo-Ultra-v1-PRO
        path: dist/KSO_Download_Turbo_Ultra_v1.exe
